// frontend/src/app/components/ui/progress.tsx
"use client";

import * as React from "react";
import * as ProgressPrimitive from "@radix-ui/react-progress";

import { cn } from "./utils";

function Progress({
  className,
  value,
  style,
  ...props
}: React.ComponentProps<typeof ProgressPrimitive.Root>) {
  return (
    <ProgressPrimitive.Root
      data-slot="progress"
      className={cn(
        "bg-primary/20 relative h-2 w-full overflow-hidden rounded-full",
        className,
      )}
      {...props}
    >
      <ProgressPrimitive.Indicator
        data-slot="progress-indicator"
        className="bg-primary h-full w-full flex-1 transition-all"
        style={{
          transform: `translateX(-${100 - (value || 0)}%)`,
          backgroundColor: (style as any)?.['--progress-background'] || undefined
        }}
      />
    </ProgressPrimitive.Root>
  );
}

export { Progress };

// frontend-v2/src/lib/components/ui/progress/progress.svelte
<script lang="ts">
	import { cn } from '$lib/utils';
	import type { Snippet } from 'svelte';

	type Props = {
		class?: string;
		value?: number;
		max?: number;
		children?: Snippet;
		[key: string]: unknown;
	};

	let { class: className, value = 0, max = 100, children, ...restProps }: Props = $props();

	const percentage = $derived(Math.min(100, Math.max(0, (value / max) * 100)));
</script>

<div
	data-slot="progress"
	role="progressbar"
	aria-valuenow={value}
	aria-valuemin={0}
	aria-valuemax={max}
	class={cn('flex flex-wrap gap-3', className)}
	{...restProps}
>
	{#if children}
		{@render children()}
	{/if}
	<div
		data-slot="progress-track"
		class="relative flex h-3 w-full items-center overflow-x-hidden rounded-full bg-muted"
	>
		<div
			data-slot="progress-indicator"
			class="h-full bg-primary transition-all"
			style="width: {percentage}%"
		></div>
	</div>
</div>
