// faiz-ui-app/src/components/ui/slider.tsx
import { Slider as SliderPrimitive } from "@base-ui/react/slider"

import { cn } from "@/lib/utils"

function Slider({
  className,
  defaultValue,
  value,
  min = 0,
  max = 100,
  ...props
}: SliderPrimitive.Root.Props) {
  const _values = Array.isArray(value)
    ? value
    : Array.isArray(defaultValue)
      ? defaultValue
      : [min, max]

  return (
    <SliderPrimitive.Root
      className={cn("data-horizontal:w-full data-vertical:h-full", className)}
      data-slot="slider"
      defaultValue={defaultValue}
      value={value}
      min={min}
      max={max}
      thumbAlignment="edge"
      {...props}
    >
      <SliderPrimitive.Control className="relative flex w-full touch-none items-center select-none data-disabled:opacity-50 data-vertical:h-full data-vertical:min-h-40 data-vertical:w-auto data-vertical:flex-col">
        <SliderPrimitive.Track
          data-slot="slider-track"
          className="relative grow overflow-hidden rounded-full bg-input/90 select-none data-horizontal:h-2 data-horizontal:w-full data-vertical:h-full data-vertical:w-2"
        >
          <SliderPrimitive.Indicator
            data-slot="slider-range"
            className="bg-primary select-none data-horizontal:h-full data-vertical:w-full"
          />
        </SliderPrimitive.Track>
        {Array.from({ length: _values.length }, (_, index) => (
          <SliderPrimitive.Thumb
            data-slot="slider-thumb"
            key={index}
            className="block h-4 w-6 shrink-0 rounded-full bg-white shadow-md ring-1 ring-black/10 transition-[color,box-shadow,background-color] select-none not-dark:bg-clip-padding hover:ring-4 hover:ring-ring/30 focus-visible:ring-4 focus-visible:ring-ring/30 focus-visible:outline-hidden disabled:pointer-events-none disabled:opacity-50 data-vertical:h-6 data-vertical:w-4"
          />
        ))}
      </SliderPrimitive.Control>
    </SliderPrimitive.Root>
  )
}

export { Slider }

// frontend-v2/src/lib/components/ui/slider/slider.svelte
<script lang="ts">
	import { Slider as SliderPrimitive } from 'bits-ui';
	import { cn } from '$lib/utils';

	type Props = {
		class?: string;
		value?: number[];
		onValueChange?: (value: number[]) => void;
		min?: number;
		max?: number;
		step?: number;
		disabled?: boolean;
		orientation?: 'horizontal' | 'vertical';
		[key: string]: unknown;
	};

	let {
		class: className,
		value = $bindable([0]),
		onValueChange,
		min = 0,
		max = 100,
		step = 1,
		disabled = false,
		orientation = 'horizontal',
		...restProps
	}: Props = $props();
</script>

<SliderPrimitive.Root
	bind:value
	{onValueChange}
	{min}
	{max}
	{step}
	{disabled}
	{orientation}
	data-slot="slider"
	class={cn('relative flex w-full touch-none select-none items-center', className)}
	{...restProps}
>
	<SliderPrimitive.Track
		data-slot="slider-track"
		class="relative h-2 w-full grow overflow-hidden rounded-full bg-input/90"
	>
		<SliderPrimitive.Range data-slot="slider-range" class="absolute h-full bg-primary" />
	</SliderPrimitive.Track>
	{#each value as _, i}
		<SliderPrimitive.Thumb
			index={i}
			data-slot="slider-thumb"
			class="block h-4 w-6 shrink-0 rounded-full border-2 border-primary bg-background shadow-md ring-0 transition-colors focus-visible:ring-4 focus-visible:ring-ring/30 focus-visible:outline-none disabled:pointer-events-none disabled:opacity-50"
		/>
	{/each}
</SliderPrimitive.Root>
