// frontend-v2/src/lib/components/ui/collapsible/collapsible.svelte
<script lang="ts">
	import { Collapsible as CollapsiblePrimitive } from 'bits-ui';
	import type { Snippet } from 'svelte';

	type Props = {
		open?: boolean;
		onOpenChange?: (open: boolean) => void;
		disabled?: boolean;
		children?: Snippet;
		[key: string]: unknown;
	};

	let {
		open = $bindable(false),
		onOpenChange,
		disabled = false,
		children,
		...restProps
	}: Props = $props();
</script>

<CollapsiblePrimitive.Root bind:open {onOpenChange} {disabled} data-slot="collapsible" {...restProps}>
	{#if children}
		{@render children()}
	{/if}
</CollapsiblePrimitive.Root>

// faiz-ui-app/src/components/ui/collapsible.tsx
import { Collapsible as CollapsiblePrimitive } from "@base-ui/react/collapsible"

function Collapsible({ ...props }: CollapsiblePrimitive.Root.Props) {
  return <CollapsiblePrimitive.Root data-slot="collapsible" {...props} />
}

function CollapsibleTrigger({ ...props }: CollapsiblePrimitive.Trigger.Props) {
  return (
    <CollapsiblePrimitive.Trigger data-slot="collapsible-trigger" {...props} />
  )
}

function CollapsibleContent({ ...props }: CollapsiblePrimitive.Panel.Props) {
  return (
    <CollapsiblePrimitive.Panel data-slot="collapsible-content" {...props} />
  )
}

export { Collapsible, CollapsibleContent, CollapsibleTrigger }
