// frontend-v2/src/lib/components/ui/toggle-group.svelte
<script lang="ts" module>
	import { getContext, setContext } from 'svelte';
	import type { ToggleVariant, ToggleSize } from './toggle.svelte';

	export type ToggleGroupContext = {
		variant: ToggleVariant;
		size: ToggleSize;
		spacing: number;
		orientation: 'horizontal' | 'vertical';
		value: string[];
		toggle: (val: string) => void;
		type: 'single' | 'multiple';
	};

	const TOGGLE_GROUP_KEY = Symbol('toggle-group');

	export function getToggleGroupContext(): ToggleGroupContext | undefined {
		return getContext<ToggleGroupContext>(TOGGLE_GROUP_KEY);
	}

	export function setToggleGroupContext(ctx: ToggleGroupContext) {
		setContext(TOGGLE_GROUP_KEY, ctx);
	}
</script>

<script lang="ts">
	import { cn } from '$lib/utils';
	import type { HTMLAttributes } from 'svelte/elements';
	import type { Snippet } from 'svelte';

	type Props = HTMLAttributes<HTMLDivElement> & {
		variant?: ToggleVariant;
		size?: ToggleSize;
		spacing?: number;
		orientation?: 'horizontal' | 'vertical';
		type?: 'single' | 'multiple';
		value?: string[];
		children?: Snippet;
	};

	let {
		class: className,
		variant = 'default',
		size = 'default',
		spacing = 2,
		orientation = 'horizontal',
		type = 'single',
		value = $bindable([]),
		children,
		...restProps
	}: Props = $props();

	function toggle(val: string) {
		if (type === 'single') {
			value = value.includes(val) ? [] : [val];
		} else {
			value = value.includes(val) ? value.filter((v) => v !== val) : [...value, val];
		}
	}

	setToggleGroupContext({
		get variant() {
			return variant;
		},
		get size() {
			return size;
		},
		get spacing() {
			return spacing;
		},
		get orientation() {
			return orientation;
		},
		get value() {
			return value;
		},
		toggle,
		get type() {
			return type;
		}
	});
</script>

<div
	data-slot="toggle-group"
	data-variant={variant}
	data-size={size}
	data-spacing={spacing}
	data-orientation={orientation}
	role="group"
	style="--gap: {spacing}"
	class={cn(
		'group/toggle-group flex w-fit flex-row items-center gap-[--spacing(var(--gap))] data-[spacing=0]:data-[variant=outline]:rounded-3xl data-[orientation=vertical]:flex-col data-[orientation=vertical]:items-stretch',
		className
	)}
	{...restProps}
>
	{#if children}
		{@render children()}
	{/if}
</div>

// faiz-ui-app/src/components/ui/toggle-group.tsx
import { Toggle as TogglePrimitive } from "@base-ui/react/toggle"
import { ToggleGroup as ToggleGroupPrimitive } from "@base-ui/react/toggle-group"
import type { VariantProps } from "class-variance-authority"
import * as React from "react"
import { toggleVariants } from "@/components/ui/toggle"
import { cn } from "@/lib/utils"

const ToggleGroupContext = React.createContext<
  VariantProps<typeof toggleVariants> & {
    spacing?: number
    orientation?: "horizontal" | "vertical"
  }
>({
  size: "default",
  variant: "default",
  spacing: 2,
  orientation: "horizontal",
})

function ToggleGroup({
  className,
  variant,
  size,
  spacing = 2,
  orientation = "horizontal",
  children,
  ...props
}: ToggleGroupPrimitive.Props &
  VariantProps<typeof toggleVariants> & {
    spacing?: number
    orientation?: "horizontal" | "vertical"
  }) {
  return (
    <ToggleGroupPrimitive
      data-slot="toggle-group"
      data-variant={variant}
      data-size={size}
      data-spacing={spacing}
      data-orientation={orientation}
      style={{ "--gap": spacing } as React.CSSProperties}
      className={cn(
        "group/toggle-group flex w-fit flex-row items-center gap-[--spacing(var(--gap))] data-[spacing=0]:data-[variant=outline]:rounded-3xl data-vertical:flex-col data-vertical:items-stretch",
        className
      )}
      {...props}
    >
      <ToggleGroupContext.Provider
        value={{ variant, size, spacing, orientation }}
      >
        {children}
      </ToggleGroupContext.Provider>
    </ToggleGroupPrimitive>
  )
}

function ToggleGroupItem({
  className,
  children,
  variant = "default",
  size = "default",
  ...props
}: TogglePrimitive.Props & VariantProps<typeof toggleVariants>) {
  const context = React.useContext(ToggleGroupContext)

  return (
    <TogglePrimitive
      data-slot="toggle-group-item"
      data-variant={context.variant || variant}
      data-size={context.size || size}
      data-spacing={context.spacing}
      className={cn(
        "shrink-0 group-data-[spacing=0]/toggle-group:rounded-none group-data-[spacing=0]/toggle-group:px-3 group-data-[spacing=0]/toggle-group:shadow-none focus:z-10 focus-visible:z-10 group-data-[spacing=0]/toggle-group:has-data-[icon=inline-end]:pr-2.5 group-data-[spacing=0]/toggle-group:has-data-[icon=inline-start]:pl-2.5 group-data-horizontal/toggle-group:data-[spacing=0]:first:rounded-l-3xl group-data-vertical/toggle-group:data-[spacing=0]:first:rounded-t-3xl group-data-horizontal/toggle-group:data-[spacing=0]:last:rounded-r-3xl group-data-vertical/toggle-group:data-[spacing=0]:last:rounded-b-3xl data-[state=on]:bg-muted group-data-horizontal/toggle-group:data-[spacing=0]:data-[variant=outline]:border-l-0 group-data-vertical/toggle-group:data-[spacing=0]:data-[variant=outline]:border-t-0 group-data-horizontal/toggle-group:data-[spacing=0]:data-[variant=outline]:first:border-l group-data-vertical/toggle-group:data-[spacing=0]:data-[variant=outline]:first:border-t",
        toggleVariants({
          variant: context.variant || variant,
          size: context.size || size,
        }),
        className
      )}
      {...props}
    >
      {children}
    </TogglePrimitive>
  )
}

export { ToggleGroup, ToggleGroupItem }
